server:
  port: 8080

spring:
  application:
    name: transaction-management

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true 